# Generated by Django 4.2.9 on 2024-03-07 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='아이템 고유 아이디')),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image_url', models.URLField(max_length=512, verbose_name='이미지 URL')),
                ('amount', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='유저 아이템 고유 아이디')),
                ('amount', models.PositiveIntegerField(verbose_name='수량')),
                ('used_amount', models.PositiveIntegerField(default=0, verbose_name='사용 수량')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item_pivot', to='items.item', verbose_name='아이템 고유 아이디')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': 'user item',
                'verbose_name_plural': 'user items',
                'db_table': 'user_item',
            },
        ),
        migrations.CreateModel(
            name='UserItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='유저 아이템 로그 고유 아이디')),
                ('used_at', models.DateTimeField(verbose_name='사용 일시')),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item_logs', to='items.useritem', verbose_name='유저 아이템 고유 아이디')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': 'user item log',
                'verbose_name_plural': 'user item logs',
                'db_table': 'user_item_log',
            },
        ),
    ]
