# Generated by Django 4.2.9 on 2024-02-03 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
        ('channels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item_pivot', to=settings.AUTH_USER_MODEL, verbose_name='유저 고유 아이디'),
        ),
        migrations.AddField(
            model_name='item',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='channels.channel', verbose_name='채널 고유 아이디'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_item',
            field=models.ManyToManyField(related_name='items', through='items.UserItem', to=settings.AUTH_USER_MODEL, verbose_name='유저 아이템'),
        ),
    ]
