# Generated by Django 4.2.9 on 2024-02-03 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='수량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useritem',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='used_amount',
            field=models.PositiveIntegerField(default=1999, verbose_name='사용 수량'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useritem',
            unique_together={('item', 'user')},
        ),
        migrations.CreateModel(
            name='UserItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='유저 아이템 로그 고유 아이디')),
                ('used_at', models.DateTimeField(verbose_name='사용 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item_logs', to='items.useritem', verbose_name='유저 아이템 고유 아이디')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': 'user item log',
                'verbose_name_plural': 'user item logs',
                'db_table': 'user_item_log',
            },
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='used_at',
        ),
    ]
