# Generated by Django 4.2.9 on 2024-02-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_useritem_amount_useritem_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='used_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='사용 수량'),
        ),
    ]
