# Generated by Django 4.2.9 on 2024-03-07 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='게시판 고유 아이디')),
                ('main_title', models.CharField(max_length=32, verbose_name='메인 제목')),
                ('sub_title', models.CharField(max_length=64, verbose_name='서브 제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateField(verbose_name='날짜')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='channels.channel', verbose_name='채널 고유 아이디')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'post',
            },
        ),
    ]
