# Generated by Django 4.2.9 on 2024-02-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0003_channel_market_closing_at_channel_market_opening_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='주식 고유 아이디')),
                ('name', models.CharField(max_length=32, verbose_name='종목명')),
                ('purchase_price', models.PositiveIntegerField(verbose_name='매입가격')),
                ('next_day_purchase_price', models.PositiveIntegerField(verbose_name='다음날 매입가격')),
                ('tax', models.FloatField(verbose_name='세금')),
                ('standard', models.CharField(max_length=32, verbose_name='기준')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='channels.channel', verbose_name='채널 고유 아이디')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='UserTradeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='거래 정보 고유 아이디')),
                ('trade_date', models.DateField(verbose_name='거래 일자')),
                ('trade_type', models.IntegerField(verbose_name='거래 유형')),
                ('price', models.PositiveIntegerField(verbose_name='단가')),
                ('amount', models.PositiveIntegerField(verbose_name='수량')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trade_info_pivot', to='stocks.stock', verbose_name='주식 고유 아이디')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trade_info_pivot', to=settings.AUTH_USER_MODEL, verbose_name='유저 고유 아이디')),
            ],
            options={
                'verbose_name': 'user trade info',
                'verbose_name_plural': 'user trade infos',
                'db_table': 'user_trade_info',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='user_trade_info',
            field=models.ManyToManyField(related_name='stock', through='stocks.UserTradeInfo', to=settings.AUTH_USER_MODEL, verbose_name='유저 주식 정보'),
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='일별 시세 고유 아이디')),
                ('trade_date', models.DateField(verbose_name='거래 일자')),
                ('price', models.PositiveIntegerField(verbose_name='주가')),
                ('volume', models.PositiveIntegerField(verbose_name='거래량')),
                ('transaction_amount', models.PositiveIntegerField(verbose_name='거래 대금')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.stock', verbose_name='주식 고유 아이디')),
            ],
            options={
                'verbose_name': 'daily price',
                'verbose_name_plural': 'daily prices',
                'db_table': 'daily_price',
                'indexes': [models.Index(fields=['trade_date'], name='daily_price_trade_d_1daca7_idx')],
            },
        ),
    ]
