# Generated by Django 4.2.9 on 2024-02-07 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_stock_prev_day_purchase_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together={('trade_date', 'stock')},
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='유저 주식 고유 아이디')),
                ('total_stock_amount', models.PositiveIntegerField(verbose_name='총 주식 수량')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='stocks.stock', verbose_name='주식 고유 아이디')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to=settings.AUTH_USER_MODEL, verbose_name='유저 고유 아이디')),
            ],
            options={
                'verbose_name': 'user stock',
                'verbose_name_plural': 'user stocks',
                'db_table': 'user_stock',
                'unique_together': {('stock', 'user')},
            },
        ),
    ]
