# Generated by Django 4.2.11 on 2024-03-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_userstock_stock_alter_userstock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='standard',
            field=models.PositiveIntegerField(default=0, verbose_name='기준'),
        ),
    ]
