# Generated by Django 4.2.9 on 2024-03-07 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channel_pivot', to=settings.AUTH_USER_MODEL, verbose_name='유저 고유 아이디'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to=settings.AUTH_USER_MODEL, verbose_name='유저 고유 아이디'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user_channel',
            field=models.ManyToManyField(related_name='channel', through='channels.UserChannel', to=settings.AUTH_USER_MODEL, verbose_name='유저 채널'),
        ),
        migrations.AlterUniqueTogether(
            name='userchannel',
            unique_together={('user', 'channel')},
        ),
    ]
