# Generated by Django 4.2.9 on 2024-02-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='market_closing_at',
            field=models.TimeField(default='15:00:00', verbose_name='시장 종료 시간'),
        ),
        migrations.AddField(
            model_name='channel',
            name='market_opening_at',
            field=models.TimeField(default='09:00:00', verbose_name='시장 시작 시간'),
        ),
    ]
